// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjislxmkntaunloeqdzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqaXNseG1rbnRhdW5sb2VxZHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzAxOTYsImV4cCI6MjA2ODMwNjE5Nn0.s-v4Vcb4OojbnuDYFVo-RaLcIyakAIikhPueZYmDOoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});